package com.mealplanner.domain;

import java.io.Serializable;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "PLACEHOLDER_MEALS_TABLE_NAME")
public class Meal implements Serializable {

    private static final long serialVersionUID = 6245212145624127225L;

    @DynamoDBRangeKey(attributeName = "mealId")
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBHashKey
    private String userId;

    @DynamoDBAttribute
    private String description;

    public String getId() {
        return id;
    }

    public void setId(final String id) {
        this.id = id;
    }

    public String getUserId() {
        return userId;
    }

    public void setUserId(final String userId) {
        this.userId = userId;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(final String description) {
        this.description = description;
    }

    @Override
    public String toString() {
        return "Meal [id=" + id + ", userId=" + userId + ", description=" + description + "]";
    }
}
